---
title: "Presentation with shiny"
runtime: shiny
output: ioslides_presentation
author: Yanfei Kang
date: 8 May, 2015
---

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the parameters underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Slide with Interactive Table

```{r, echo = FALSE}
numericInput("rows", "How many cars?", 5)

renderTable({
  head(cars, input$rows)
})
```

## Slide with Interactive Plot

```{r, echo = FALSE,results='asis'}
inputPanel(
  
  selectInput("fmethod",label = "Forecasting method:", choices=c('Mean','Naive','Snaive')),
  
  sliderInput('h',label = "Forecasting horizon",min = 1, max = 20, value = 1, step=1)
  
)

renderPlot({
  library(fpp)
  beer2 <- window(ausbeer,start=1992,end=2006-.1)
  if (input$fmethod == 'Mean'){
    beerfit <- meanf(beer2,h=input$h)
  }else if (input$fmethod == 'Naive'){
    beerfit <- rwf(beer2,h=input$h)
  }else{
    beerfit <- snaive(beer2,h=input$h)
  }

  plot(beerfit,plot.conf=FALSE,main="Forecasts for quarterly beer production")

},width = 800, height = 300)
```

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3



